# Generated by Django 4.1.7 on 2023-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collage',
            fields=[
                ('collageId', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('collageName', models.TextField(max_length=100)),
                ('collageDescription', models.TextField(max_length=550)),
            ],
        ),
    ]
