# Generated by Django 4.1.7 on 2023-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meet',
            fields=[
                ('collageId', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('collageName', models.TextField(max_length=100)),
                ('collageDescription', models.TextField(max_length=550)),
                ('collageImage', models.ImageField(upload_to='collage/')),
            ],
        ),
    ]
