# Generated by Django 4.1.7 on 2023-03-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_delete_collage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meet',
            new_name='collage',
        ),
    ]
