# Generated by Django 4.1.7 on 2023-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_rename_meet_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='vinit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collageName', models.TextField(max_length=100)),
                ('collageDescription', models.TextField(max_length=550)),
                ('collageImage', models.ImageField(upload_to='collage/')),
            ],
        ),
        migrations.DeleteModel(
            name='collage',
        ),
    ]
