# Generated by Django 4.1.7 on 2023-03-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_vinit_delete_collage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vinit',
            new_name='collage',
        ),
    ]
