# Generated by Django 4.1.7 on 2023-03-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=200)),
                ('collageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.collage')),
            ],
        ),
    ]
