# Generated by Django 4.1.7 on 2023-03-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('collageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.collage')),
            ],
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
