# Generated by Django 4.1.7 on 2023-03-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_dept_delete_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dept',
            new_name='department',
        ),
    ]
