# Generated by Django 4.1.7 on 2023-03-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_meet_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meet',
            new_name='user',
        ),
    ]
