# Generated by Django 4.1.7 on 2023-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_rename_meet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
    ]
